openapi: 3.0.3
info:
  title: RAG Chatbot API for Physical AI & Humanoid Robotics Book
  description: API for interacting with the RAG chatbot system
  version: 1.0.0
  contact:
    name: Development Team
    email: dev@physicalai-book.com

servers:
  - url: https://api.physicalai-book.com/v1
    description: Production server
  - url: https://staging-api.physicalai-book.com/v1
    description: Staging server

paths:
  /chat:
    post:
      summary: Send a message to the chatbot
      description: Submit a question to the RAG chatbot and receive an answer based on book content
      operationId: sendMessage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatRequest'
      responses:
        '200':
          description: Successful response from the chatbot
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatResponse'
        '400':
          description: Bad request - invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '429':
          description: Rate limit exceeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - api_key: []

  /chat/selected:
    post:
      summary: Ask about selected text
      description: Submit a question about selected text on a page to the RAG chatbot
      operationId: sendSelectedTextMessage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SelectedTextChatRequest'
      responses:
        '200':
          description: Successful response from the chatbot based on selected text
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatResponse'
        '400':
          description: Bad request - invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '429':
          description: Rate limit exceeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - api_key: []

  /sessions/{sessionId}:
    get:
      summary: Get chat session history
      description: Retrieve the history of messages in a chat session
      operationId: getSessionHistory
      parameters:
        - name: sessionId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: The session ID
      responses:
        '200':
          description: Session history retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionHistoryResponse'
        '404':
          description: Session not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - api_key: []

  /content/search:
    get:
      summary: Search book content
      description: Search for content in the book using semantic search
      operationId: searchContent
      parameters:
        - name: query
          in: query
          required: true
          schema:
            type: string
          description: Search query
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 20
            default: 10
          description: Number of results to return
        - name: content_type
          in: query
          required: false
          schema:
            type: string
            enum: [chapter, section, subsection, figure, table]
          description: Filter by content type
      responses:
        '200':
          description: Search results retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResponse'
        '400':
          description: Bad request - invalid parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - api_key: []

components:
  schemas:
    ChatRequest:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: The user's message/question
          example: "What is the main principle of physical AI?"
        session_id:
          type: string
          format: uuid
          description: The session ID (optional, will be created if not provided)
          example: "550e8400-e29b-41d4-a716-446655440000"
        page_url:
          type: string
          description: The URL of the current page (for context)
          example: "/docs/chapter-3/physical-ai-principles"
        selected_text:
          type: string
          description: Text selected by the user (optional, for context-specific questions)
          example: "Physical AI is the integration of artificial intelligence with physical systems..."

    SelectedTextChatRequest:
      type: object
      required:
        - message
        - selected_text
      properties:
        message:
          type: string
          description: The user's question about the selected text
          example: "Can you explain this concept more clearly?"
        selected_text:
          type: string
          description: The text selected by the user
          example: "Physical AI is the integration of artificial intelligence with physical systems..."
        session_id:
          type: string
          format: uuid
          description: The session ID (optional, will be created if not provided)
          example: "550e8400-e29b-41d4-a716-446655440000"
        page_url:
          type: string
          description: The URL of the page where text was selected
          example: "/docs/chapter-3/physical-ai-principles"

    ChatResponse:
      type: object
      required:
        - response
        - session_id
        - sources
        - timestamp
      properties:
        response:
          type: string
          description: The chatbot's response to the user's message
          example: "Physical AI is the integration of artificial intelligence with physical systems..."
        session_id:
          type: string
          format: uuid
          description: The session ID
          example: "550e8400-e29b-41d4-a716-446655440000"
        sources:
          type: array
          description: List of sources used to generate the response
          items:
            $ref: '#/components/schemas/Source'
        timestamp:
          type: string
          format: date-time
          description: The timestamp of the response
          example: "2025-12-10T10:30:00Z"
        confidence_score:
          type: number
          format: float
          minimum: 0.0
          maximum: 1.0
          description: Confidence score of the response
          example: 0.85

    Source:
      type: object
      required:
        - section_id
        - title
        - page_url
        - relevance_score
      properties:
        section_id:
          type: string
          description: Unique identifier for the content section
          example: "chapter-3-section-2"
        title:
          type: string
          description: Title of the source content
          example: "Introduction to Physical AI"
        page_url:
          type: string
          description: URL to the source page
          example: "/docs/chapter-3/section-2"
        relevance_score:
          type: number
          format: float
          minimum: 0.0
          maximum: 1.0
          description: Relevance score of the source to the query
          example: 0.92

    SessionHistoryResponse:
      type: object
      required:
        - messages
        - session_id
      properties:
        session_id:
          type: string
          format: uuid
          description: The session ID
          example: "550e8400-e29b-41d4-a716-446655440000"
        messages:
          type: array
          items:
            $ref: '#/components/schemas/Message'
        created_at:
          type: string
          format: date-time
          description: When the session was created
          example: "2025-12-10T09:00:00Z"
        updated_at:
          type: string
          format: date-time
          description: When the session was last updated
          example: "2025-12-10T10:30:00Z"

    Message:
      type: object
      required:
        - id
        - role
        - content
        - timestamp
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the message
          example: "550e8400-e29b-41d4-a716-446655440001"
        role:
          type: string
          enum: [user, assistant]
          description: The role of the message sender
          example: "user"
        content:
          type: string
          description: The content of the message
          example: "What is the main principle of physical AI?"
        timestamp:
          type: string
          format: date-time
          description: When the message was created
          example: "2025-12-10T10:29:45Z"
        sources:
          type: array
          description: Sources used in the assistant's response
          items:
            $ref: '#/components/schemas/Source'

    SearchResponse:
      type: object
      required:
        - results
      properties:
        results:
          type: array
          items:
            $ref: '#/components/schemas/SearchResult'
        query:
          type: string
          description: The original search query
          example: "physical AI principles"
        total_count:
          type: integer
          description: Total number of results available
          example: 25

    SearchResult:
      type: object
      required:
        - id
        - title
        - content_preview
        - page_url
        - relevance_score
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the content
          example: "550e8400-e29b-41d4-a716-446655440002"
        title:
          type: string
          description: Title of the content
          example: "Principles of Physical AI"
        content_preview:
          type: string
          description: Preview of the content (first 200 characters)
          example: "Physical AI is the integration of artificial intelligence with physical systems..."
        page_url:
          type: string
          description: URL to the full content
          example: "/docs/chapter-3/section-2"
        relevance_score:
          type: number
          format: float
          minimum: 0.0
          maximum: 1.0
          description: Relevance score of the content to the query
          example: 0.92
        content_type:
          type: string
          enum: [chapter, section, subsection, figure, table]
          description: Type of content
          example: "section"

    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: Error code
          example: "INVALID_INPUT"
        message:
          type: string
          description: Human-readable error message
          example: "Message content is required"
        details:
          type: object
          description: Additional error details (optional)
          example: {"field": "message"}

  securitySchemes:
    api_key:
      type: apiKey
      name: X-API-Key
      in: header
      description: API key for authentication