openapi: 3.0.3
info:
  title: RAG Chatbot API (Extended)
  description: |
    Extended /ask endpoint with user context injection for personalized responses.
    This extends the existing FastAPI backend to support authenticated users.
  version: 2.0.0
  contact:
    name: AI Book Project

servers:
  - url: https://ai-book-h6kj.onrender.com
    description: Production Backend
  - url: http://localhost:8000
    description: Local Development

tags:
  - name: Chat
    description: RAG chatbot interaction

paths:
  /ask:
    post:
      tags:
        - Chat
      summary: Ask a question with user context
      description: |
        Submit a question to the RAG chatbot with user authentication context.
        The backend personalizes response tone based on user profile while
        maintaining RAG grounding (factual content unchanged).

        **Security**: Requires valid user_id from authenticated session.
        **RAG Safety**: Profile only affects response style, not factual content.
      operationId: askQuestion
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AskRequest'
            examples:
              beginner_user:
                summary: Beginner asking about ROS2
                value:
                  question: "How do I install ROS2?"
                  context: null
                  top_k: 5
                  user_id: "usr_abc123"
                  user_profile:
                    programming_level: "beginner"
                    technologies: ["Python"]
                    hardware_access: "simulator_only"
              advanced_user:
                summary: Advanced user asking about deployment
                value:
                  question: "How do I deploy to physical hardware?"
                  context: "I'm using Isaac Sim for testing"
                  top_k: 5
                  user_id: "usr_xyz789"
                  user_profile:
                    programming_level: "advanced"
                    technologies: ["Python", "ROS2", "AI/ML"]
                    hardware_access: "real_robots"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AskResponse'
              example:
                question: "How do I install ROS2?"
                answer: |
                  Let me walk you through installing ROS2 step by step...
                  [Simplified explanation for beginner]
                sources:
                  - url: "https://book.example.com/chapter1/install"
                    content: "ROS2 installation requires..."
                retrieval_time_ms: 150
                generation_time_ms: 1200
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                detail: "Invalid programming_level: must be beginner, intermediate, or advanced"
        '401':
          description: Authentication required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                detail: "user_id is required"
        '422':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'

  /health:
    get:
      tags:
        - Health
      summary: Health check
      description: Returns server health status
      operationId: healthCheck
      responses:
        '200':
          description: Server is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "healthy"

components:
  schemas:
    AskRequest:
      type: object
      required:
        - question
        - user_id
        - user_profile
      properties:
        question:
          type: string
          minLength: 1
          maxLength: 2000
          description: User's question for the chatbot
          example: "How do I install ROS2 on Ubuntu?"
        context:
          type: string
          nullable: true
          maxLength: 5000
          description: Optional selected text context from the book
          example: "I'm reading about simulation environments"
        top_k:
          type: integer
          minimum: 1
          maximum: 10
          default: 5
          description: Number of source documents to retrieve
        user_id:
          type: string
          description: Authenticated user ID from Better Auth session
          example: "usr_abc123xyz"
        user_profile:
          $ref: '#/components/schemas/UserProfile'

    UserProfile:
      type: object
      required:
        - programming_level
        - technologies
        - hardware_access
      properties:
        programming_level:
          type: string
          enum:
            - beginner
            - intermediate
            - advanced
          description: |
            User's programming experience level.
            - beginner: Little to no programming experience
            - intermediate: Comfortable with programming basics
            - advanced: Experienced developer
        technologies:
          type: array
          items:
            type: string
            enum:
              - Python
              - JS
              - ROS2
              - AI/ML
              - Web
              - Other
          minItems: 0
          description: Technologies the user is familiar with
          example: ["Python", "ROS2"]
        hardware_access:
          type: string
          enum:
            - none
            - simulator_only
            - real_robots
          description: |
            User's hardware access level.
            - none: No hardware or simulator access
            - simulator_only: Access to simulation environments only
            - real_robots: Access to physical robot hardware

    AskResponse:
      type: object
      required:
        - question
        - answer
        - sources
        - retrieval_time_ms
        - generation_time_ms
      properties:
        question:
          type: string
          description: The original question
        answer:
          type: string
          description: |
            AI-generated answer, personalized to user's level.
            **RAG Safety**: Content is always grounded in retrieved sources.
            Only tone and complexity are adjusted based on profile.
        sources:
          type: array
          items:
            $ref: '#/components/schemas/Source'
          description: Retrieved source documents
        retrieval_time_ms:
          type: number
          format: float
          description: Time taken for vector search (ms)
        generation_time_ms:
          type: number
          format: float
          description: Time taken for LLM generation (ms)

    Source:
      type: object
      required:
        - url
        - content
      properties:
        url:
          type: string
          format: uri
          description: Source document URL
        content:
          type: string
          maxLength: 500
          description: Truncated content snippet

    ErrorResponse:
      type: object
      properties:
        detail:
          type: string
          description: Error message

    ValidationError:
      type: object
      properties:
        detail:
          type: array
          items:
            type: object
            properties:
              loc:
                type: array
                items:
                  type: string
              msg:
                type: string
              type:
                type: string
